export const weatherCodes = {
  0: [`Clear sky`, `sunny-outline`],
  1: [`Mainly clear`, `cloud-outline`],
  2: [`Partly cloudy`, `partly-sunny`],
  3: [`Overcast`, `cloud`],
  45: [`Fog`, `cloud-offline`],
  48: [`Rime fog`, `cloud-offline`],
  51: [`Light drizzle`, `water-outline`],
  53: [`Moderate drizzle`, `water`],
  55: [`Dense drizzle`, `water`],
  56: [`Light freezing drizzle`, `thermometer-outline`],
  57: [`Dense freezing drizzle`, `thermometer`],
  61: [`Slight rain`, `rainy-outline`],
  63: [`Moderate rain`, `rainy-outline`],
  65: [`Heavy rain`, `rainy`],
  66: [`Light freezing rain`, `ice-cream-outline`],
  67: [`Heavy freezing rain`, `ice-cream`],
  71: [`Slight snow fall`, `snow-outline`],
  73: [`Moderate snow fall`, `snow-outline`],
  75: [`Heavy snow fall`, `snow`],
  77: [`Snow grains`, `snow`],
  80: [`Slight rain showers`, `rainy-outline`],
  81: [`Moderate rain showers`, `rainy-outline`],
  82: [`Violent rain showers`, `rainy`],
  85: [`Slight snow showers`, `snow-outline`],
  86: [`Heavy snow showers`, `snow`],
  95: [`Thunderstorm`, `thunderstorm-outline`],
  96: [`Thunderstorm with hail`, `thunderstorm`],
  99: [`Thunderstorm with hail`, `thunderstorm`],
};
